Repository serlo/serlo.org-cloudflare-worker, pull requests merged in 2021-01, with the labels that each got.

#84 utils: Shorten query in getPathInfo()
  src/utils/index.tsx
Labels: refactoring

#130 use probabilies for mobile authed and desktop users
  README.md
  __tests__/__utils__/index.ts
  __tests__/frontend-proxy.ts
  jest.setup.ts
  src/frontend-proxy.ts
  src/vars.d.ts
  wrangler.toml
Labels: 100% Frontend

#137 Bugfix: Resolve legal pages before redirects
  src/index.ts
Labels: bug

#146 Fix e2e tests in embed.ts
  __tests__/embed.ts
Labels: refactoring

#144 Use fetchSerlo() in tests for redircts HTTP -> HTTPS
  __tests__/__utils__/fetch-helper.ts
  __tests__/index.ts
Labels: refactoring

#133 tests: Use fetchSerlo()
  README.md
  __tests__/__utils__/fetch-helper.ts
  __tests__/api.ts
  __tests__/embed.ts
  __tests__/index.ts
  __tests__/redirects.ts
  package.json
  yarn.lock
Labels: refactoring

#154 Some improvements for src/embed.ts
  __tests__/embed.ts
  src/embed.ts
Labels: enhancement
